export const routes = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  supervisorDashboard: "/supervisor/dashboard",
  supervisorApplications: "/supervisor/rider-applications",
  supervisorRiders: "/supervisor/riders",
  supervisorCustomers: "/supervisor/customers",
  supervisorIssues: "/supervisor/issues",
  adminDashboard: "/admin/dashboard",
  adminSupervisors: "/admin/supervisors",
  adminApprovals: "/admin/rider-approvals",
  adminUsers: "/admin/users",
  adminRiders: "/admin/riders",
  adminDeliveries: "/admin/deliveries",
  adminDisputes: "/admin/disputes",
  adminRefunds: "/admin/refunds",
  adminTransactions: "/admin/finance/transactions",
  adminPayouts: "/admin/finance/payouts",
  adminCommissions: "/admin/finance/commissions",
  adminAnalytics: "/admin/analytics",
  adminAuditLogs: "/admin/audit-logs",
  profile: "/profile",
  changePassword: "/change-password",
  notifications: "/notifications",
} as const;
