import type { CustomerOrder, CustomerUser } from "./types";

export const mockCustomersSeed: CustomerUser[] = [
  {
    id: "usr-cst-001",
    name: "Olawale Adebayo",
    firstName: "Olawale",
    lastName: "Adebayo",
    email: "olawale.adebayo@gmail.com",
    phoneNumber: "+2348031234567",
    roles: ["Customer"],
    status: "Active",
    hasSupportFlag: false,
    createdOn: "2026-06-15T10:30:00Z",
    lastOnlineAt: "2026-08-19T22:14:00Z",
  },
  {
    id: "usr-cst-002",
    name: "Chidimma Eze",
    firstName: "Chidimma",
    lastName: "Eze",
    email: "chidimma.eze@yahoo.com",
    phoneNumber: "+2348129876543",
    roles: ["Customer"],
    status: "Active",
    hasSupportFlag: true,
    createdOn: "2026-07-02T14:20:00Z",
    lastOnlineAt: "2026-08-19T18:05:00Z",
  },
  {
    id: "usr-cst-003",
    name: "Babajide Ogundele",
    firstName: "Babajide",
    lastName: "Ogundele",
    email: "babajide.o@outlook.com",
    phoneNumber: "+2347055551234",
    roles: ["Customer"],
    status: "Suspended",
    hasSupportFlag: false,
    createdOn: "2026-05-11T09:00:00Z",
    lastOnlineAt: "2026-08-10T11:40:00Z",
  },
  {
    id: "usr-cst-004",
    name: "Fatima Bello",
    firstName: "Fatima",
    lastName: "Bello",
    email: "fatima.bello@trustroute.ng",
    phoneNumber: "+2348091112233",
    roles: ["Customer"],
    status: "Active",
    hasSupportFlag: false,
    createdOn: "2026-07-19T16:45:00Z",
    lastOnlineAt: "2026-08-19T23:50:00Z",
  },
  {
    id: "usr-cst-005",
    name: "Emeka Okafor",
    firstName: "Emeka",
    lastName: "Okafor",
    email: "emeka.okafor@gmail.com",
    phoneNumber: "+2348184445566",
    roles: ["Customer"],
    status: "Restricted",
    hasSupportFlag: true,
    createdOn: "2026-04-30T11:15:00Z",
    lastOnlineAt: "2026-08-15T08:30:00Z",
  },
];

export const mockCustomerOrdersSeed: Record<string, CustomerOrder[]> = {
  "usr-cst-001": [
    {
      id: "DEL-8841",
      senderName: "Olawale Adebayo",
      senderEmail: "olawale.adebayo@gmail.com",
      riderName: "Tunde Bakare",
      pickupLocation: "12 Allen Avenue, Ikeja, Lagos",
      dropoffLocation: "45 Admiralty Way, Lekki Phase 1, Lagos",
      status: "Delivered",
      price: 4500,
      createdOn: "2026-08-18T14:30:00Z",
      hasException: false,
    },
    {
      id: "DEL-8890",
      senderName: "Olawale Adebayo",
      senderEmail: "olawale.adebayo@gmail.com",
      riderName: "Ibrahim Sani",
      pickupLocation: "Plot 8 Victoria Island, Lagos",
      dropoffLocation: "22 Commercial Avenue, Yaba, Lagos",
      status: "InTransit",
      price: 3200,
      createdOn: "2026-08-19T16:10:00Z",
      hasException: false,
    },
  ],
  "usr-cst-002": [
    {
      id: "DEL-8712",
      senderName: "Chidimma Eze",
      senderEmail: "chidimma.eze@yahoo.com",
      riderName: "Suleiman Garba",
      pickupLocation: "15 Isaac John St, Ikeja GRA, Lagos",
      dropoffLocation: "100 Awolowo Road, Ikoyi, Lagos",
      status: "Delivered",
      price: 5800,
      createdOn: "2026-08-12T11:00:00Z",
      hasException: false,
    },
    {
      id: "DEL-8805",
      senderName: "Chidimma Eze",
      senderEmail: "chidimma.eze@yahoo.com",
      riderName: "Unassigned",
      pickupLocation: "Marina Bus Stop, Lagos Island",
      dropoffLocation: "Surulere Shopping Mall, Lagos",
      status: "Cancelled",
      price: 2800,
      createdOn: "2026-08-15T09:20:00Z",
      hasException: true,
    },
  ],
};
