import type { RiderReviewRecord } from "./types";

const documentBase = "/images/ops-warehouse-floor.jpg";

function documents(complete = true) {
  return [
    {
      type: "nin",
      label: "NIN slip",
      fileName: "nin-slip.jpg",
      fileType: "image",
      url: documentBase,
      verified: true,
    },
    {
      type: "drivers_license",
      label: "Driver's license",
      fileName: "drivers-license.pdf",
      fileType: "pdf",
      url: documentBase,
      verified: complete,
    },
    {
      type: "voters_card",
      label: "Voter's Card",
      fileName: "voters-card.jpg",
      fileType: "image",
      url: documentBase,
      verified: true,
    },
    {
      type: "relative_one_id",
      label: "Relative 1 ID",
      fileName: "relative-one-id.jpg",
      fileType: "image",
      url: documentBase,
      verified: true,
    },
    {
      type: "relative_two_id",
      label: "Relative 2 ID",
      fileName: "relative-two-id.jpg",
      fileType: "image",
      url: documentBase,
      verified: complete,
    },
  ] as const;
}

export const riderApplicationsSeed: RiderReviewRecord[] = [
  {
    id: "RAP-1028",
    riderId: "RID-4028",
    name: "Chinedu Okeke",
    email: "chinedu.okeke@example.com",
    phone: "+234 801 334 9021",
    city: "Lagos",
    address: "18 Allen Avenue, Ikeja, Lagos",
    status: "Pending Verification",
    submittedAt: "Today, 09:42",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(true)],
    vehicle: { type: "Motorbike", plateNumber: "KJA-482-QK", color: "Black", capacity: "Small parcels" },
    nextOfKin: { name: "Ada Okeke", phone: "+234 803 772 1010", relationship: "Sister" },
    relatives: [
      { name: "Uche Okeke", relationship: "Brother", phone: "+234 805 221 3418" },
      { name: "Ifeoma Nwankwo", relationship: "Aunt", phone: "+234 809 432 1098" },
    ],
    checks: [
      { label: "Identity consistency", status: "Passed" },
      { label: "Document quality", status: "Passed" },
      { label: "Vehicle plate check", status: "Needs Review" },
    ],
    notes: "Clear documents. Plate lookup should be confirmed before final activation.",
  },
  {
    id: "RAP-1024",
    riderId: "RID-4024",
    name: "Mariam Yusuf",
    email: "mariam.yusuf@example.com",
    phone: "+234 802 110 9844",
    city: "Abuja",
    address: "Plot 44 Adetokunbo Ademola Crescent, Wuse II, Abuja",
    status: "More Info Required",
    submittedAt: "Yesterday, 16:10",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(false)],
    vehicle: { type: "Car", plateNumber: "ABC-783-MK", color: "Silver", capacity: "Medium packages" },
    nextOfKin: { name: "Bilal Yusuf", phone: "+234 803 671 1281", relationship: "Brother" },
    relatives: [
      { name: "Aisha Musa", relationship: "Cousin", phone: "+234 806 901 2844" },
      { name: "Zainab Bello", relationship: "Aunt", phone: "+234 809 553 2108" },
    ],
    checks: [
      { label: "Identity consistency", status: "Passed" },
      { label: "Document quality", status: "Needs Review" },
      { label: "Vehicle plate check", status: "Passed" },
    ],
    notes: "Driver's license and second relative ID need clearer uploads.",
  },
  {
    id: "RAP-1019",
    riderId: "RID-4019",
    name: "Victor Eze",
    email: "victor.eze@example.com",
    phone: "+234 706 443 7712",
    city: "Port Harcourt",
    address: "11 Olu Obasanjo Road, Port Harcourt",
    status: "Pending Verification",
    submittedAt: "Jul 2, 12:18",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(true)],
    vehicle: { type: "Van", plateNumber: "PHC-590-LA", color: "White", capacity: "Large packages" },
    nextOfKin: { name: "Ngozi Eze", phone: "+234 803 109 2488", relationship: "Mother" },
    relatives: [
      { name: "Kelechi Eze", relationship: "Brother", phone: "+234 802 443 5411" },
      { name: "Grace Obi", relationship: "Cousin", phone: "+234 808 311 7612" },
    ],
    checks: [
      { label: "Identity consistency", status: "Passed" },
      { label: "Document quality", status: "Passed" },
      { label: "Vehicle plate check", status: "Passed" },
    ],
    notes: "Application is complete and ready for approval.",
  },
  {
    id: "RAP-1011",
    riderId: "RID-4011",
    name: "Blessing Musa",
    email: "blessing.musa@example.com",
    phone: "+234 809 401 5572",
    city: "Ibadan",
    address: "9 Ring Road, Ibadan",
    status: "Pending Admin Review",
    submittedAt: "Jul 1, 08:31",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(true)],
    vehicle: { type: "Motorbike", plateNumber: "BDJ-192-QL", color: "Red", capacity: "Small parcels" },
    nextOfKin: { name: "Mary Musa", phone: "+234 803 232 9011", relationship: "Mother" },
    relatives: [
      { name: "Samuel Musa", relationship: "Brother", phone: "+234 806 778 1102" },
      { name: "Ruth Adamu", relationship: "Aunt", phone: "+234 802 335 8910" },
    ],
    checks: [
      { label: "Identity consistency", status: "Passed" },
      { label: "Document quality", status: "Passed" },
      { label: "Vehicle plate check", status: "Passed" },
    ],
    notes: "Supervisor review passed. Awaiting admin final decision.",
  },
  {
    id: "RAP-1008",
    riderId: "RID-4008",
    name: "Ibrahim Danjuma",
    email: "ibrahim.danjuma@example.com",
    phone: "+234 704 118 6070",
    city: "Kaduna",
    address: "23 Ahmadu Bello Way, Kaduna",
    status: "Pending Admin Review",
    submittedAt: "Jun 30, 14:27",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(true)],
    vehicle: { type: "Car", plateNumber: "KAD-774-AH", color: "Blue", capacity: "Medium packages" },
    nextOfKin: { name: "Halima Danjuma", phone: "+234 807 341 2012", relationship: "Wife" },
    relatives: [
      { name: "Sani Danjuma", relationship: "Brother", phone: "+234 803 871 2110" },
      { name: "Amina Garba", relationship: "Sister", phone: "+234 806 443 0021" },
    ],
    checks: [
      { label: "Identity consistency", status: "Passed" },
      { label: "Document quality", status: "Passed" },
      { label: "Vehicle plate check", status: "Passed" },
    ],
    notes: "Ready for admin approval.",
  },
  {
    id: "RAP-1004",
    riderId: "RID-4004",
    name: "Seyi Martins",
    email: "seyi.martins@example.com",
    phone: "+234 805 902 7744",
    city: "Lagos",
    address: "31 Admiralty Way, Lekki Phase 1",
    status: "Rejected",
    submittedAt: "Jun 29, 11:05",
    assignedSupervisor: "Amina Bello",
    documents: [...documents(false)],
    vehicle: { type: "Motorbike", plateNumber: "FKJ-019-TT", color: "Green", capacity: "Small parcels" },
    nextOfKin: { name: "Bolanle Martins", phone: "+234 809 902 4109", relationship: "Wife" },
    relatives: [
      { name: "Tayo Martins", relationship: "Brother", phone: "+234 802 902 5571" },
      { name: "Kemi Ade", relationship: "Cousin", phone: "+234 803 771 9912" },
    ],
    checks: [
      { label: "Identity consistency", status: "Failed" },
      { label: "Document quality", status: "Needs Review" },
      { label: "Vehicle plate check", status: "Passed" },
    ],
    notes: "Rejected due to conflicting identity details.",
  },
];

export const assignedRidersSeed: RiderReviewRecord[] = [
  {
    ...riderApplicationsSeed[0],
    id: "RID-3381",
    riderId: "RID-3381",
    name: "Tunde Salami",
    email: "tunde.salami@example.com",
    status: "Active",
    submittedAt: "Approved Jun 12",
    rating: "4.8",
    completedDeliveries: 184,
    activeIssues: 0,
    lastOnline: "7 min ago",
    notes: "Reliable on Lagos Island routes.",
  },
  {
    ...riderApplicationsSeed[1],
    id: "RID-3314",
    riderId: "RID-3314",
    name: "Fatima Lawal",
    email: "fatima.lawal@example.com",
    status: "Active",
    submittedAt: "Approved Jun 8",
    rating: "4.7",
    completedDeliveries: 139,
    activeIssues: 1,
    lastOnline: "22 min ago",
    notes: "One active late pickup issue under review.",
  },
  {
    ...riderApplicationsSeed[2],
    id: "RID-3279",
    riderId: "RID-3279",
    name: "Emeka Nwosu",
    email: "emeka.nwosu@example.com",
    status: "Under Review",
    submittedAt: "Approved May 22",
    rating: "4.2",
    completedDeliveries: 71,
    activeIssues: 2,
    lastOnline: "Yesterday",
    notes: "Temporary review due to repeated package photo misses.",
  },
  {
    ...riderApplicationsSeed[3],
    id: "RID-3251",
    riderId: "RID-3251",
    name: "Blessing Musa",
    status: "Suspended",
    submittedAt: "Approved May 18",
    rating: "4.5",
    completedDeliveries: 96,
    activeIssues: 1,
    lastOnline: "2 days ago",
    notes: "Suspended pending final incident review.",
  },
];
